version: '3.8'

services:
  # Build the base image
  formation-base:
    build:
      context: .
      dockerfile: Dockerfile
    image: formation/base:latest

# Example of how to extend the base image in a service-specific Dockerfile:
#
# FROM formation/base:latest
#
# # Install service-specific dependencies
# RUN apt-get update -y && \
#     apt-get install -y <service-specific-packages> && \
#     apt-get clean && \
#     rm -rf /var/lib/apt/lists/*
#
# # Copy service binary
# COPY ./target/release/<service-name> /usr/local/bin/
#
# # Copy startup script
# COPY ./scripts/run-<service-name>.sh /usr/local/bin/
# RUN chmod +x /usr/local/bin/run-<service-name>.sh
#
# # Create service-specific directories
# RUN mkdir -p /var/lib/formation/<service-specific-dirs>
#
# # Expose service ports
# EXPOSE <service-port>
#
# # Set entrypoint
# ENTRYPOINT ["/usr/local/bin/run-<service-name>.sh"] 