version: '3.8'

# Formation platform minimal docker-compose configuration
services:
  # DNS Service
  form-dns:
    image: formationai/form-dns:latest
    container_name: formation-dns
    privileged: true
    restart: unless-stopped
    network_mode: host
    volumes:
      - dns-data:/var/lib/formation/dns
      - ./secrets/.operator-config.json:/etc/formation/operator-config.json
      - /var/run/dbus:/var/run/dbus
      - /etc/resolv.conf:/etc/resolv.conf
    environment:
      - DNS_LOG_LEVEL=info
      - DNS_API_PORT=5354
      - DNS_ROOT_DOMAIN=formation
      - DNS_STATE_URL=http://localhost:3004
      - DNS_OPERATOR_CONFIG=/etc/formation/operator-config.json
      - DNS_USE_RESOLVECTL=false
    command: ["form-dns", "run", "--dns-port", "5354"]
    healthcheck:
      test: ["CMD", "dig", "@127.0.0.1", "-p", "5354", "formation"]
      interval: 5s
      timeout: 10s
      retries: 3

  # State Service
  form-state:
    image: formationai/form-state:latest
    container_name: formation-state
    network_mode: host
    volumes:
      - state-data:/var/lib/formation/db
      - ./secrets/.operator-config.json:/etc/formation/operator-config.json
    environment:
      - STATE_LOG_LEVEL=info
      - STATE_DB_PATH=/var/lib/formation/db/formation.db
      - STATE_API_PORT=3004
      - STATE_CONFIG_PATH=/etc/formation/operator-config.json
      - STATE_PASSWORD=${FORMATION_PASSWORD:-formation-password}
      - AUTH_MODE=development
      - DYNAMIC_JWKS_URL=https://app.dynamic.xyz/api/v0/sdk/3f53e601-17c7-419b-8a13-4c5e25c0bde9/.well-known/jwks
    command: ["/usr/local/bin/form-state", "--config", "/etc/formation/operator-config.json", "--encrypted", "--password", "${FORMATION_PASSWORD:-formation-password}"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3004/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  # Virtual Machine Manager Service
  vmm-service:
    image: formationai/vmm-service:latest
    container_name: formation-vmm
    depends_on:
      - form-state
    network_mode: host
    volumes:
      - vm-images:/var/lib/formation/vm-images
      - kernel-data:/var/lib/formation/kernel
      - /run/form-vm:/run/form-vm
      - ./secrets/.operator-config.json:/etc/formation/operator-config.json
    environment:
      - VMM_LOG_LEVEL=info
      - VMM_STATE_URL=http://localhost:3004
      - VMM_API_PORT=3003
      - VMM_CONFIG_PATH=/etc/formation/operator-config.json
      - VMM_PASSWORD=${FORMATION_PASSWORD:-formation-password}
      - VMM_KERNEL_PATH=/var/lib/formation/kernel/hypervisor-fw
      - VMM_VM_DIR=/run/form-vm
      - VMM_IMAGES_DIR=/var/lib/formation/vm-images
      - RUST_BACKTRACE=1
    command: ["vmm-service", "run"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    privileged: true
    network_mode: "host" # Use host networking for better VM performance
    devices:
      - /dev/kvm
      - /dev/vhost-net
      - /dev/null 
      - /dev/zero
      - /dev/random
      - /dev/urandom
    tmpfs:
      - /dev/hugepages:mode=1770
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    restart: unless-stopped

  # Package Manager Service
  form-pack-manager:
    image: formationai/form-pack-manager:latest
    container_name: formation-pack-manager
    depends_on:
      - form-state
    network_mode: host
    volumes:
      - pack-data:/var/lib/formation/pack-manager
      - ./secrets/.operator-config.json:/etc/formation/pack-manager/config.json
    environment:
      - PACK_MANAGER_LOG_LEVEL=info
      - PACK_MANAGER_PORT=8080
      - PACK_MANAGER_INTERFACE=all
      - PACK_MANAGER_CONFIG_PATH=/etc/formation/pack-manager/config.json
      - PACK_MANAGER_PASSWORD=${FORMATION_PASSWORD:-formation-password}
      - PACK_MANAGER_DATA_DIR=/var/lib/formation/pack-manager
      - PACK_MANAGER_ENCRYPTED=true
    command: ["form-pack-manager", "--interface", "all", "--port", "8080", "--config", "/etc/formation/pack-manager/config.json", "--password", "${FORMATION_PASSWORD:-formation-password}"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    privileged: true  # Needed for image building
    restart: unless-stopped

  # Network Service
  formnet:
    image: formationai/formnet:latest
    container_name: formation-network
    depends_on:
      - form-state
    network_mode: host
    volumes:
      - net-data:/var/lib/formnet
      - ./secrets/.operator-config.json:/etc/formnet/config.json
    environment:
      - FORMNET_LOG_LEVEL=info
      - FORMNET_CONFIG_DIR=/etc/formnet
      - FORMNET_DATA_DIR=/var/lib/formnet
      - FORMNET_NETWORK_NAME=formnet
      - FORMNET_SERVER_PORT=8080
      - FORMNET_LISTEN_PORT=51820
      - FORMNET_EXTERNAL_ENDPOINT=auto
    command: ["formnet", "operator", "join", "--config-path", "/etc/formnet/config.json"]
    cap_add:
      - NET_ADMIN
    privileged: true
    restart: unless-stopped

# Volumes configuration
volumes:
  # DNS volumes
  dns-data:
    driver: local
  
  # State volumes
  state-data:
    driver: local
  
  # VM volumes
  vm-images:
    driver: local
  kernel-data:
    driver: local
  
  # Package manager volumes
  pack-data:
    driver: local
  
  # Network volumes
  net-data:
    driver: local
  
  # Secrets volume (create this directory on your host)
  secrets:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /path/to/your/secrets  # Update this path 
