services:
  local-ai-host:
    image: localai/localai:latest-cpu
    container_name: local-ai-host
    ports:
      - "8080:8080"
    command: ["run", "--p2p", "--p2ptoken", "b3RwOgogIGRodDoKICAgIGludGVydmFsOiAzNjAKICAgIGtleTogajNmdjFBWnA3SG40RWduOHNZY2FqbnpaY3ZKTDg1UVNvVURoZFlESzNrSgogICAgbGVuZ3RoOiA0MwogIGNyeXB0bzoKICAgIGludGVydmFsOiA5MDAwCiAgICBrZXk6IG5YdkpiTnBzeVJ5eGpFRlNJTmJlNXNFdWR3dWlpNmtUZE4zdzNrbndUR2QKICAgIGxlbmd0aDogNDMKcm9vbTogS04yUUx6THdpWnFWc3N2alFXektzSVE3T2ZBa1p6V0c0c2FCQlNNVFd6YwpyZW5kZXp2b3VzOiAwQXNkZXRiQU5rNzNoTDJyQlJvMHYwdUxTVWg3Y2RseUdDRlNkdjUzb0NFCm1kbnM6IElzYkJWREdiSVFzWlRyZ0c3aXFIVk82T0xOeXdCcG1oaFh3STdsVGdEN0sKbWF4X21lc3NhZ2Vfc2l6ZTogMjA5NzE1MjAK"]

  local-ai-worker1:
    image: localai/localai:latest-cpu
    container_name: local-ai-worker1
    network_mode: host
    environment:
      - TOKEN=b3RwOgogIGRodDoKICAgIGludGVydmFsOiAzNjAKICAgIGtleTogajNmdjFBWnA3SG40RWduOHNZY2FqbnpaY3ZKTDg1UVNvVURoZFlESzNrSgogICAgbGVuZ3RoOiA0MwogIGNyeXB0bzoKICAgIGludGVydmFsOiA5MDAwCiAgICBrZXk6IG5YdkpiTnBzeVJ5eGpFRlNJTmJlNXNFdWR3dWlpNmtUZE4zdzNrbndUR2QKICAgIGxlbmd0aDogNDMKcm9vbTogS04yUUx6THdpWnFWc3N2alFXektzSVE3T2ZBa1p6V0c0c2FCQlNNVFd6YwpyZW5kZXp2b3VzOiAwQXNkZXRiQU5rNzNoTDJyQlJvMHYwdUxTVWg3Y2RseUdDRlNkdjUzb0NFCm1kbnM6IElzYkJWREdiSVFzWlRyZ0c3aXFIVk82T0xOeXdCcG1oaFh3STdsVGdEN0sKbWF4X21lc3NhZ2Vfc2l6ZTogMjA5NzE1MjAK
    command: ["worker", "p2p-llama-cpp-rpc"]

  local-ai-worker2:
    image: localai/localai:latest-cpu
    container_name: local-ai-worker2
    network_mode: host
    environment:
      - TOKEN=b3RwOgogIGRodDoKICAgIGludGVydmFsOiAzNjAKICAgIGtleTogajNmdjFBWnA3SG40RWduOHNZY2FqbnpaY3ZKTDg1UVNvVURoZFlESzNrSgogICAgbGVuZ3RoOiA0MwogIGNyeXB0bzoKICAgIGludGVydmFsOiA5MDAwCiAgICBrZXk6IG5YdkpiTnBzeVJ5eGpFRlNJTmJlNXNFdWR3dWlpNmtUZE4zdzNrbndUR2QKICAgIGxlbmd0aDogNDMKcm9vbTogS04yUUx6THdpWnFWc3N2alFXektzSVE3T2ZBa1p6V0c0c2FCQlNNVFd6YwpyZW5kZXp2b3VzOiAwQXNkZXRiQU5rNzNoTDJyQlJvMHYwdUxTVWg3Y2RseUdDRlNkdjUzb0NFCm1kbnM6IElzYkJWREdiSVFzWlRyZ0c3aXFIVk82T0xOeXdCcG1oaFh3STdsVGdEN0sKbWF4X21lc3NhZ2Vfc2l6ZTogMjA5NzE1MjAK
    command: ["worker", "p2p-llama-cpp-rpc"]

